### ISSUE TITLE
checkincurrentdirectory(libname) will not find ilorest_chif.so

### ISSUE THREAD

**Issue by trusnak** [HewlettPackard/python-ilorest-library#53]
In redfish/hpilo/risblobstore2.py: checkincurrdirectory(libname) you are searching for path where the library is placed. For the ilorest_chif.so it is:
```
$ dpkg -L ilorest 
/usr/lib/x86_64-linux-gnu/ilorest_chif.so
```
on line 897 you can find:
```
os.getenv("LD_LIBRARY_PATH",  'ilorest_chif.so').split(';')
['ilorest_chif.so']
```
This not the path you should use to find the library in. As the result the library was not found, because other 2 checks are returning - /usr/bin/ilorest_chif.so and /root/ilorest_chif.so

**Comment by iLORESTeam** [comment]
Are you referencing a specific error? CTypes should be able to find the shared object file, if it has been placed in the correct location. (For Debian x86-64, yes, '/usr/lib/x86-64-linux-gnu/ilorest_chif.so') 
You may try directly from the interpreter:
from redfish.hpilo.risblobstore2 import BlobStore2
print BlobStore2.gethprestchifhandle()

**Comment by trusnak** [comment]
Your example will end up with this error:
```
In [1]: from redfish.hpilo.risblobstore2 import BlobStore2
In [2]: BlobStore2.gethprestchifhandle()
---------------------------------------------------------------------------
ChifDllMissingError                       Traceback (most recent call last)
<ipython-input-2-d777eff35ae6> in <module>()
----> 1 BlobStore2.gethprestchifhandle()

/usr/lib/python3/dist-packages/redfish/hpilo/risblobstore2.py in gethprestchifhandle()
    835             BlobStore2.setglobalhprestchifrandnumber(libhandle)
    836             return libhandle
--> 837         raise ChifDllMissingError(excp)
    838 
    839     @staticmethod
ChifDllMissingError: '_Environ' object has no attribute 'has_key'
```
Let me explain my problem with example:
```
In [1]: import redfish
In [2]: redfish.redfish_client('blobstore://.', 'Administrator', 'Administrator')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-4a48a4eb3f85> in <module>()
----> 1 redfish.redfish_client('blobstore://.', 'Administrator', 'Administrator')

/usr/lib/python3/dist-packages/redfish/rest/v1.py in get_client_instance(base_url, username, password, default_prefix, biospassword, sessionkey, is_redfish, cache, proxy)
   1224                             default_prefix=default_prefix, username=username, \
   1225                             password=password, sessionkey=sessionkey, \
-> 1226                             is_redfish=is_redfish, cache=cache, proxy=proxy)
   1227     else:
   1228         return HttpClient(base_url=base_url, username=username, \

/usr/lib/python3/dist-packages/redfish/rest/v1.py in __init__(self, base_url, default_prefix, username, password, sessionkey, is_redfish, cache, proxy)
    964             raise ChifDriverMissingOrNotFound()
    965         except Exception as excp:
--> 966             if excp.message == 'chif':
    967                 raise ChifDriverMissingOrNotFound()
    968             else:

AttributeError: 'ChifDllMissingError' object has no attribute 'message'
```

**Comment by trusnak** [comment]
You are still using has_key on dict which is deprecated/removed in python3, but this only part of the problem (that's for your example from previous comment). 
The method checkincurrdirectory(libname) is checking environment LD_LIBRARY_PATH variable for library path, but that doesn't work on my system (Ubuntu 16.04).

**Comment by Yergidy** [comment]
We are fixing the python 3 has_key issue. LD_LIBRARY_PATH is one of a few locations we check for the library. If none of these locations are found we pass the so name itself to ctypes, which checks more locations. Ctypes checks many more locations for the so before returning an error. I believe the python 3 issue is raising an error before the code is getting to that point.

**Comment by Yergidy** [comment]
Fixed in version 2.5.2: https://github.com/HewlettPackard/python-ilorest-library/releases/tag/v2.5.2
